// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _24_Esercizio.Data;

#nullable disable

namespace _24_Esercizio.Migrations
{
    [DbContext(typeof(AutoreLibroContext))]
    [Migration("20251113095136_init3")]
    partial class init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("_24_Esercizio.Model.Autore", b =>
                {
                    b.Property<string>("AutoreId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataDiNascita")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AutoreId");

                    b.ToTable("Autori");
                });

            modelBuilder.Entity("_24_Esercizio.Model.Libro", b =>
                {
                    b.Property<string>("LibroID")
                        .HasColumnType("TEXT");

                    b.Property<string>("AutoreId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Anno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pagine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LibroID", "AutoreId");

                    b.ToTable("Libri");
                });
#pragma warning restore 612, 618
        }
    }
}
